name: preflight # You can also change this to another name to avoid warning with existing group. 
services:
  backend:
    container_name: pf-backend
    build: .
    ports:
      - ${PORT}:3000
    networks:
      - preflight_pf-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
networks:
  preflight_pf-net: # Check by using `docker network ls` command
    external: true