name: todo-14 # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: g14-todo-frontend
    build: .
    ports:
      - ${NGINX_PORT}:5114
    networks:
      - g14-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  g14-net: # Check by using `docker network ls` command
    external: true