name: todo-14
services:
  postgres:
    image: postgres:16-alpine
    container_name: g14-todo-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g14-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g14-net
volumes:
  g14-data:
    name: g14-data
networks:
  g14-net:
    name: g14-net
